title: Moon
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
#plugins:
#  - jekyll-feed

include: 
  - _pages 
  - _pages/research_01
  - _pages/research_02
  - _pages/research_03 
  - _pages/research_04
  - _pages/research_05
  - _pages/research_06

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
